services:
  - type: web
    name: cold-email-system
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: BASE_URL
        value: https://email-campaign-system.onrender.com
      - key: MONGODB_URI
        sync: false
      - key: LOG_LEVEL
        value: info
    autoDeploy: true
    healthCheckPath: /health